import { StudentMastery, Topic } from "./types";

export const topics: Topic[] = [
    { id: "t1", name: "Fundamentals", category: "Core" },
    { id: "t2", name: "SDLC Testing", category: "Core" },
    { id: "t3", name: "Static Testing", category: "Techniques" },
    { id: "t4", name: "Test Design", category: "Techniques" },
    { id: "t5", name: "Test Management", category: "Management" },
    { id: "t6", name: "Tool Support", category: "Tools" },
    { id: "t7", name: "Agile Testing", category: "Methodologies" },
    { id: "t8", name: "Risk Analysis", category: "Management" },
];

export const mockStudentMastery: StudentMastery[] = [
    {
        studentId: "s1",
        studentName: "Alex Johnson",
        overallMastery: 78,
        lastActive: new Date("2026-01-03"),
        topicScores: {
            t1: { topicId: "t1", topicName: "Fundamentals", score: 92, questionsAttempted: 25, questionsCorrect: 23, trend: "stable", lastAttempt: new Date() },
            t2: { topicId: "t2", topicName: "SDLC Testing", score: 85, questionsAttempted: 20, questionsCorrect: 17, trend: "improving", lastAttempt: new Date() },
            t3: { topicId: "t3", topicName: "Static Testing", score: 76, questionsAttempted: 18, questionsCorrect: 14, trend: "stable", lastAttempt: new Date() },
            t4: { topicId: "t4", topicName: "Test Design", score: 68, questionsAttempted: 22, questionsCorrect: 15, trend: "improving", lastAttempt: new Date() },
            t5: { topicId: "t5", topicName: "Test Management", score: 72, questionsAttempted: 15, questionsCorrect: 11, trend: "stable", lastAttempt: new Date() },
            t6: { topicId: "t6", topicName: "Tool Support", score: 88, questionsAttempted: 12, questionsCorrect: 11, trend: "stable", lastAttempt: new Date() },
            t7: { topicId: "t7", topicName: "Agile Testing", score: 65, questionsAttempted: 10, questionsCorrect: 7, trend: "declining", lastAttempt: new Date() },
            t8: { topicId: "t8", topicName: "Risk Analysis", score: 78, questionsAttempted: 14, questionsCorrect: 11, trend: "improving", lastAttempt: new Date() },
        },
    },
    {
        studentId: "s2",
        studentName: "Maria Garcia",
        overallMastery: 85,
        lastActive: new Date("2026-01-03"),
        topicScores: {
            t1: { topicId: "t1", topicName: "Fundamentals", score: 95, questionsAttempted: 28, questionsCorrect: 27, trend: "stable", lastAttempt: new Date() },
            t2: { topicId: "t2", topicName: "SDLC Testing", score: 88, questionsAttempted: 22, questionsCorrect: 19, trend: "stable", lastAttempt: new Date() },
            t3: { topicId: "t3", topicName: "Static Testing", score: 82, questionsAttempted: 20, questionsCorrect: 16, trend: "improving", lastAttempt: new Date() },
            t4: { topicId: "t4", topicName: "Test Design", score: 90, questionsAttempted: 25, questionsCorrect: 22, trend: "stable", lastAttempt: new Date() },
            t5: { topicId: "t5", topicName: "Test Management", score: 78, questionsAttempted: 18, questionsCorrect: 14, trend: "improving", lastAttempt: new Date() },
            t6: { topicId: "t6", topicName: "Tool Support", score: 75, questionsAttempted: 15, questionsCorrect: 11, trend: "stable", lastAttempt: new Date() },
            t7: { topicId: "t7", topicName: "Agile Testing", score: 85, questionsAttempted: 12, questionsCorrect: 10, trend: "stable", lastAttempt: new Date() },
            t8: { topicId: "t8", topicName: "Risk Analysis", score: 88, questionsAttempted: 16, questionsCorrect: 14, trend: "stable", lastAttempt: new Date() },
        },
    },
    {
        studentId: "s3",
        studentName: "James Wilson",
        overallMastery: 52,
        lastActive: new Date("2026-01-02"),
        topicScores: {
            t1: { topicId: "t1", topicName: "Fundamentals", score: 68, questionsAttempted: 20, questionsCorrect: 14, trend: "improving", lastAttempt: new Date() },
            t2: { topicId: "t2", topicName: "SDLC Testing", score: 55, questionsAttempted: 15, questionsCorrect: 8, trend: "stable", lastAttempt: new Date() },
            t3: { topicId: "t3", topicName: "Static Testing", score: 42, questionsAttempted: 12, questionsCorrect: 5, trend: "declining", lastAttempt: new Date() },
            t4: { topicId: "t4", topicName: "Test Design", score: 35, questionsAttempted: 18, questionsCorrect: 6, trend: "declining", lastAttempt: new Date() },
            t5: { topicId: "t5", topicName: "Test Management", score: 58, questionsAttempted: 10, questionsCorrect: 6, trend: "stable", lastAttempt: new Date() },
            t6: { topicId: "t6", topicName: "Tool Support", score: 62, questionsAttempted: 8, questionsCorrect: 5, trend: "improving", lastAttempt: new Date() },
            t7: { topicId: "t7", topicName: "Agile Testing", score: 48, questionsAttempted: 6, questionsCorrect: 3, trend: "stable", lastAttempt: new Date() },
            t8: { topicId: "t8", topicName: "Risk Analysis", score: 50, questionsAttempted: 10, questionsCorrect: 5, trend: "stable", lastAttempt: new Date() },
        },
    },
    {
        studentId: "s4",
        studentName: "Sarah Chen",
        overallMastery: 91,
        lastActive: new Date("2026-01-03"),
        topicScores: {
            t1: { topicId: "t1", topicName: "Fundamentals", score: 98, questionsAttempted: 30, questionsCorrect: 29, trend: "stable", lastAttempt: new Date() },
            t2: { topicId: "t2", topicName: "SDLC Testing", score: 94, questionsAttempted: 25, questionsCorrect: 23, trend: "stable", lastAttempt: new Date() },
            t3: { topicId: "t3", topicName: "Static Testing", score: 88, questionsAttempted: 22, questionsCorrect: 19, trend: "stable", lastAttempt: new Date() },
            t4: { topicId: "t4", topicName: "Test Design", score: 92, questionsAttempted: 28, questionsCorrect: 26, trend: "stable", lastAttempt: new Date() },
            t5: { topicId: "t5", topicName: "Test Management", score: 85, questionsAttempted: 20, questionsCorrect: 17, trend: "improving", lastAttempt: new Date() },
            t6: { topicId: "t6", topicName: "Tool Support", score: 90, questionsAttempted: 18, questionsCorrect: 16, trend: "stable", lastAttempt: new Date() },
            t7: { topicId: "t7", topicName: "Agile Testing", score: 88, questionsAttempted: 15, questionsCorrect: 13, trend: "stable", lastAttempt: new Date() },
            t8: { topicId: "t8", topicName: "Risk Analysis", score: 92, questionsAttempted: 18, questionsCorrect: 17, trend: "stable", lastAttempt: new Date() },
        },
    },
    {
        studentId: "s5",
        studentName: "Michael Brown",
        overallMastery: 38,
        lastActive: new Date("2026-01-01"),
        topicScores: {
            t1: { topicId: "t1", topicName: "Fundamentals", score: 55, questionsAttempted: 15, questionsCorrect: 8, trend: "improving", lastAttempt: new Date() },
            t2: { topicId: "t2", topicName: "SDLC Testing", score: 32, questionsAttempted: 10, questionsCorrect: 3, trend: "stable", lastAttempt: new Date() },
            t3: { topicId: "t3", topicName: "Static Testing", score: 28, questionsAttempted: 8, questionsCorrect: 2, trend: "declining", lastAttempt: new Date() },
            t4: { topicId: "t4", topicName: "Test Design", score: 25, questionsAttempted: 12, questionsCorrect: 3, trend: "declining", lastAttempt: new Date() },
            t5: { topicId: "t5", topicName: "Test Management", score: 45, questionsAttempted: 8, questionsCorrect: 4, trend: "stable", lastAttempt: new Date() },
            t6: { topicId: "t6", topicName: "Tool Support", score: 0, questionsAttempted: 0, questionsCorrect: 0, trend: "stable", lastAttempt: new Date() },
            t7: { topicId: "t7", topicName: "Agile Testing", score: 52, questionsAttempted: 5, questionsCorrect: 3, trend: "improving", lastAttempt: new Date() },
            t8: { topicId: "t8", topicName: "Risk Analysis", score: 38, questionsAttempted: 6, questionsCorrect: 2, trend: "stable", lastAttempt: new Date() },
        },
    },
    {
        studentId: "s6",
        studentName: "Emily Davis",
        overallMastery: 72,
        lastActive: new Date("2026-01-03"),
        topicScores: {
            t1: { topicId: "t1", topicName: "Fundamentals", score: 82, questionsAttempted: 22, questionsCorrect: 18, trend: "stable", lastAttempt: new Date() },
            t2: { topicId: "t2", topicName: "SDLC Testing", score: 75, questionsAttempted: 18, questionsCorrect: 14, trend: "stable", lastAttempt: new Date() },
            t3: { topicId: "t3", topicName: "Static Testing", score: 68, questionsAttempted: 16, questionsCorrect: 11, trend: "improving", lastAttempt: new Date() },
            t4: { topicId: "t4", topicName: "Test Design", score: 72, questionsAttempted: 20, questionsCorrect: 14, trend: "stable", lastAttempt: new Date() },
            t5: { topicId: "t5", topicName: "Test Management", score: 65, questionsAttempted: 14, questionsCorrect: 9, trend: "stable", lastAttempt: new Date() },
            t6: { topicId: "t6", topicName: "Tool Support", score: 78, questionsAttempted: 12, questionsCorrect: 9, trend: "improving", lastAttempt: new Date() },
            t7: { topicId: "t7", topicName: "Agile Testing", score: 70, questionsAttempted: 10, questionsCorrect: 7, trend: "stable", lastAttempt: new Date() },
            t8: { topicId: "t8", topicName: "Risk Analysis", score: 68, questionsAttempted: 12, questionsCorrect: 8, trend: "stable", lastAttempt: new Date() },
        },
    },
];
