import { Course } from "./types";

export const mockCourses: Course[] = [
    {
        id: "c1",
        title: "ISTQB Foundation Level",
        description: "Complete preparation for the ISTQB FL certification exam with comprehensive modules covering all syllabus topics.",
        progress: 67,
        duration: "24 hours",
        lessons: 48,
        category: "certification",
        level: "beginner",
        instructor: "Dr. Sarah Mitchell",
        rating: 4.8,
        studentsEnrolled: 2450,
        tags: ["ISTQB", "Certification", "Foundation"],
        isFeatured: true,
        lastAccessed: new Date("2026-01-03"),
        startDate: "2026-02-01T09:00",
        endDate: "2026-05-01T17:00",
        attachmentUrl: "https://example.com/syllabus.pdf"
    },
    {
        id: "c2",
        title: "Test Design Techniques",
        description: "Master black-box and white-box testing techniques including equivalence partitioning, boundary value analysis, and decision tables.",
        progress: 45,
        duration: "8 hours",
        lessons: 16,
        category: "testing-techniques",
        level: "intermediate",
        instructor: "Alex Thompson",
        rating: 4.6,
        studentsEnrolled: 1820,
        tags: ["Black-box", "White-box", "Test Design"],
        lastAccessed: new Date("2026-01-02"),
    },
    {
        id: "c3",
        title: "Agile Testing Essentials",
        description: "Learn testing practices in agile development environments. Cover Scrum, Kanban, and continuous testing strategies.",
        progress: 23,
        duration: "6 hours",
        lessons: 12,
        category: "agile",
        level: "beginner",
        instructor: "Maria Garcia",
        rating: 4.7,
        studentsEnrolled: 1560,
        tags: ["Agile", "Scrum", "CI/CD"],
        lastAccessed: new Date("2026-01-01"),
    },
    {
        id: "c4",
        title: "Selenium WebDriver Masterclass",
        description: "Comprehensive automation testing with Selenium WebDriver. Learn Java, Python, and Page Object Model patterns.",
        progress: 0,
        duration: "18 hours",
        lessons: 36,
        category: "automation",
        level: "intermediate",
        instructor: "James Wilson",
        rating: 4.9,
        studentsEnrolled: 3200,
        tags: ["Selenium", "Automation", "WebDriver"],
        isNew: true,
    },
    {
        id: "c5",
        title: "API Testing with Postman & REST Assured",
        description: "Master API testing from basics to advanced concepts. Build robust API test frameworks and automation suites.",
        progress: 0,
        duration: "10 hours",
        lessons: 22,
        category: "automation",
        level: "intermediate",
        instructor: "Chen Wei",
        rating: 4.8,
        studentsEnrolled: 2100,
        tags: ["API", "Postman", "REST"],
        isNew: true,
    },
    {
        id: "c6",
        title: "ISTQB Advanced Test Analyst",
        description: "Advanced certification prep covering test analysis, design techniques, and quality characteristics testing.",
        progress: 0,
        duration: "32 hours",
        lessons: 64,
        category: "certification",
        level: "advanced",
        instructor: "Dr. Sarah Mitchell",
        rating: 4.7,
        studentsEnrolled: 890,
        tags: ["ISTQB", "Advanced", "Test Analyst"],
    },
    {
        id: "c7",
        title: "Performance Testing Fundamentals",
        description: "Learn JMeter, LoadRunner basics, and performance testing strategies for web applications.",
        progress: 12,
        duration: "12 hours",
        lessons: 24,
        category: "tools",
        level: "intermediate",
        instructor: "Michael Brown",
        rating: 4.5,
        studentsEnrolled: 1340,
        tags: ["Performance", "JMeter", "Load Testing"],
        lastAccessed: new Date("2025-12-28"),
    },
    {
        id: "c8",
        title: "Communication for QA Professionals",
        description: "Develop essential communication skills for bug reporting, stakeholder management, and team collaboration.",
        progress: 0,
        duration: "4 hours",
        lessons: 8,
        category: "soft-skills",
        level: "beginner",
        instructor: "Emily Davis",
        rating: 4.4,
        studentsEnrolled: 760,
        tags: ["Communication", "Soft Skills", "Reporting"],
    },
    {
        id: "c9",
        title: "Mobile App Testing",
        description: "Testing strategies for iOS and Android applications using Appium, Espresso, and XCUITest.",
        progress: 0,
        duration: "14 hours",
        lessons: 28,
        category: "automation",
        level: "advanced",
        instructor: "Raj Patel",
        rating: 4.6,
        studentsEnrolled: 1120,
        tags: ["Mobile", "Appium", "iOS", "Android"],
    },
    {
        id: "c10",
        title: "DevOps for Testers",
        description: "CI/CD pipelines, Docker, Kubernetes basics, and integrating testing into DevOps workflows.",
        progress: 5,
        duration: "16 hours",
        lessons: 32,
        category: "agile",
        level: "advanced",
        instructor: "Alex Thompson",
        rating: 4.8,
        studentsEnrolled: 1890,
        tags: ["DevOps", "CI/CD", "Docker"],
        lastAccessed: new Date("2025-12-20"),
    },
];
