import { FlashcardDeck, Flashcard } from "./types";

export const mockDecks: FlashcardDeck[] = [
    {
        id: "deck1",
        name: "ISTQB Fundamentals",
        description: "Core testing concepts, principles, and terminology",
        category: "Certification",
        cardCount: 45,
        masteredCount: 28,
        dueCount: 12,
        color: "from-violet-500 to-purple-600",
        icon: "BookOpen",
        lastStudied: new Date("2026-01-03"),
    },
    {
        id: "deck2",
        name: "Test Design Techniques",
        description: "Black-box and white-box testing methods",
        category: "Techniques",
        cardCount: 32,
        masteredCount: 15,
        dueCount: 8,
        color: "from-amber-500 to-orange-600",
        icon: "PenTool",
        lastStudied: new Date("2026-01-02"),
    },
    {
        id: "deck3",
        name: "Agile Testing",
        description: "Testing in Scrum, Kanban, and CI/CD environments",
        category: "Methodologies",
        cardCount: 24,
        masteredCount: 10,
        dueCount: 5,
        color: "from-emerald-500 to-teal-600",
        icon: "Zap",
        lastStudied: new Date("2026-01-01"),
    },
    {
        id: "deck4",
        name: "Test Management",
        description: "Planning, estimation, monitoring, and defect management",
        category: "Management",
        cardCount: 28,
        masteredCount: 8,
        dueCount: 15,
        color: "from-blue-500 to-cyan-600",
        icon: "BarChart3",
    },
    {
        id: "deck5",
        name: "Automation Concepts",
        description: "Test automation principles and tool selection",
        category: "Automation",
        cardCount: 20,
        masteredCount: 5,
        dueCount: 10,
        color: "from-pink-500 to-rose-600",
        icon: "Bot",
    },
];

export const mockFlashcards: Record<string, Flashcard[]> = {
    "deck1": [
        {
            id: "fc1-1",
            deckId: "deck1",
            front: "What is the primary objective of software testing?",
            back: "To find defects before the software is released to users, and to provide confidence in the level of quality of the software.",
            hint: "Think about quality assurance goals",
            difficulty: "mastered",
            correctCount: 8,
            incorrectCount: 1,
            streak: 5,
            lastReviewed: new Date("2026-01-02"),
        },
        {
            id: "fc1-2",
            deckId: "deck1",
            front: "List the Seven Testing Principles",
            back: "1. Testing shows presence of defects\n2. Exhaustive testing is impossible\n3. Early testing saves time and money\n4. Defects cluster together\n5. Pesticide paradox\n6. Testing is context dependent\n7. Absence-of-errors fallacy",
            difficulty: "review",
            correctCount: 5,
            incorrectCount: 2,
            streak: 3,
            lastReviewed: new Date("2026-01-01"),
        },
        {
            id: "fc1-3",
            deckId: "deck1",
            front: "What is the 'Pesticide Paradox' in testing?",
            back: "If the same tests are repeated over and over again, eventually they will no longer find new defects. Test cases need to be regularly reviewed and revised.",
            hint: "Related to test maintenance",
            difficulty: "learning",
            correctCount: 2,
            incorrectCount: 3,
            streak: 1,
        },
        {
            id: "fc1-4",
            deckId: "deck1",
            front: "What is the difference between Error, Defect, and Failure?",
            back: "Error: Human mistake that produces incorrect code\nDefect (Bug): Flaw in the software that can cause failure\nFailure: Deviation of the software from expected behavior when executed",
            difficulty: "new",
            correctCount: 0,
            incorrectCount: 0,
            streak: 0,
        },
        {
            id: "fc1-5",
            deckId: "deck1",
            front: "What are the main Test Levels?",
            back: "1. Unit/Component Testing\n2. Integration Testing\n3. System Testing\n4. Acceptance Testing",
            hint: "Think about the V-model",
            difficulty: "review",
            correctCount: 6,
            incorrectCount: 1,
            streak: 4,
            lastReviewed: new Date("2026-01-03"),
        },
        {
            id: "fc1-6",
            deckId: "deck1",
            front: "What is Regression Testing?",
            back: "Testing performed to confirm that a recent code change has not adversely affected existing features. It involves re-running previously passed tests.",
            difficulty: "mastered",
            correctCount: 10,
            incorrectCount: 0,
            streak: 10,
            lastReviewed: new Date("2026-01-03"),
        },
        {
            id: "fc1-7",
            deckId: "deck1",
            front: "Define 'Test Coverage'",
            back: "A metric that measures the amount of testing performed by a set of tests. It is expressed as a percentage of the items being tested.",
            difficulty: "learning",
            correctCount: 3,
            incorrectCount: 2,
            streak: 2,
        },
        {
            id: "fc1-8",
            deckId: "deck1",
            front: "What is the difference between Verification and Validation?",
            back: "Verification: Are we building the product right? (process-oriented)\nValidation: Are we building the right product? (product-oriented)",
            hint: "V&V - remember the questions",
            difficulty: "new",
            correctCount: 0,
            incorrectCount: 0,
            streak: 0,
        },
    ],
    "deck2": [
        {
            id: "fc2-1",
            deckId: "deck2",
            front: "What is Equivalence Partitioning?",
            back: "A black-box test design technique that divides input data into partitions of equivalent data from which test cases can be derived. One test case from each partition is typically sufficient.",
            difficulty: "mastered",
            correctCount: 7,
            incorrectCount: 1,
            streak: 6,
        },
        {
            id: "fc2-2",
            deckId: "deck2",
            front: "Explain Boundary Value Analysis",
            back: "A technique that tests at the boundaries between partitions. Boundary values include minimum, just above minimum, just below maximum, and maximum values.",
            difficulty: "review",
            correctCount: 5,
            incorrectCount: 2,
            streak: 3,
        },
        {
            id: "fc2-3",
            deckId: "deck2",
            front: "What is Decision Table Testing?",
            back: "A technique where different combinations of inputs and their corresponding system behavior are captured in a tabular form. Useful for testing business rules and complex logic.",
            difficulty: "learning",
            correctCount: 2,
            incorrectCount: 4,
            streak: 0,
        },
        {
            id: "fc2-4",
            deckId: "deck2",
            front: "Describe State Transition Testing",
            back: "A technique where tests are designed to execute valid and invalid state transitions. It uses a state diagram showing states, transitions, events, and actions.",
            difficulty: "new",
            correctCount: 0,
            incorrectCount: 0,
            streak: 0,
        },
    ],
};

export function getFlashcardsForDeck(deckId: string): Flashcard[] {
    return mockFlashcards[deckId] || [];
}

export function getDueCards(deckId: string): Flashcard[] {
    const cards = getFlashcardsForDeck(deckId);
    return cards.filter(card => card.difficulty !== "mastered" || card.streak < 5);
}
